# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH : check
    steps:
    - uses: actions/checkout@v3
    - name: Branch name
      run: echo "${GITHUB_REF##*/}" > branch;echo $branch; if [ "$branch" = "main" ] ;then  echo "branch has the value 'valid'" ; else echo "zaebka" ; fi

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
